### ISSUE TITLE
App is suspended state

### ISSUE THREAD

**Issue by vishaldeshai** [MSavisko/LocationTracker#1]
Hello,

Can this demo works when app is in suspended(terminate) state??

thanks in advance.

**Comment by MaksSaviskoTriare** [comment]
Hi!
No, only for foreground and background states.

For terminate state pls look at answer in SO:  https://stackoverflow.com/a/37453415

**Comment by MSavisko** [comment]
@vishaldeshai 
Hi!
No, only for foreground and background states.

For terminate state pls look at answer in SO:  https://stackoverflow.com/a/37453415
